In [12]:
from openai import OpenAI
from dotenv import load_dotenv
import os

load_dotenv(override=True)
api_key = os.getenv("OPENAI_API_KEY")
# print("OPENAI_API_KEY loaded:", bool(api_key))
# print(api_key[0:5])
client = OpenAI()

objects = """Vertical Stack (Left):
Wii Sports (Wii)
Wii Play (Wii)
The Sims 3 (Wii)
Deal or No Deal (Wii)
Halo 4 (Xbox 360)
Darksiders (Xbox 360)
Top Right Horizontal Stack:
Assassin's Creed (PS3)
Assassin's Creed: The Americas Collection (PS3)
Assassin's Creed Valhalla (PS4)
FIFA Soccer 13 (PS3)
FIFA Soccer 12 (PS3)
FIFA Soccer 10 (PS3)
FIFA 21 (PS4)
FIFA 19 (PS4)
FIFA 17 (PS4)
FIFA 16 (Xbox 360)
FIFA 15 (Xbox 360)
FIFA 14 (Xbox 360)
Bottom Right Horizontal Stack:
Ghost Recon: Advanced Warfighter 2 (Xbox 360)
Tom Clancy's H.A.W.X. (Xbox 360)
Call of Duty: Modern Warfare 2 (Xbox 360)
Call of Duty: Black Ops III (PS3)
Call of Duty: Modern Warfare (PS4)
Call of Duty: WWII (PS4)
Call of Duty: Infinite Warfare (PS4)
NBA Live 08 (PS3)
NBA 2K12 (PS3)
NBA 2K14 (PS3)
NBA 2K17 (PS4)
NBA 2K18 (PS4)
Madden NFL 08 (PS3)
Madden NFL 10 (PS3)
Madden NFL 19 (PS4)
Madden NFL 22 (PS4)
NCAA Football 08 (PS3)
NCAA Football 10 (PS3)
NCAA Football 11 (PS3)
Bottom Left Horizontal Stack:
007 Blood Stone (PS3)
Guitar Hero: World Tour (PS3)
Tiger Woods PGA Tour 11 (PS3)
Virtua Tennis 3 (PS3)
NASCAR 08 (PS3)
Star Wars: Battlefront (PS4)
Untamed (PS3 - possibly part of MX vs ATV series)
MX vs ATV Untamed (PS3)
NHL 12 (PS3)
NHL 13 (PS3)
Gran Turismo 6 (PS3)
F1 2011 (PS3)
Gran Turismo 5 Prologue (PS3)
Gran Turismo 5 (PS3)
MLB 08: The Show (PS3)
MLB The Show 21 (PS4)"""

response = client.responses.create(
    model="gpt-5-nano-2025-08-07",
    tools=[{"type": "web_search"}],
    input=f"Please find the prices for the used versions of the following objects. Just do your best to find the information. No need to clarify anything. {objects}"
)

print(response.output_text)

Here are best-effort used-price figures for the titles you listed, based on PriceCharting data (USD). Prices reflect typical loose/complete/new disc conditions and can vary by region, seller, and box/manual contents. Data current as of now (Dec 22, 2025).

Vertical Stack (Left)
- Wii Sports (Wii) — Loose: 24.50; Complete: 27.92; New: 44.97. ([pricecharting.com](https://www.pricecharting.com/game/wii/wii-sports))
- Wii Play (Wii) — Loose: 5.95; Complete: 6.49; New: 15.99. ([pricecharting.com](https://www.pricecharting.com/game/wii/wii-play))
- The Sims 3 (Wii) — Loose: 5.94; Complete: 7.30; New: 14.99. ([pricecharting.com](https://www.pricecharting.com/game/wii/the-sims-3))
- Deal or No Deal (Wii) — Loose: 3.82; Complete: 5.61; New: 10.45. ([pricecharting.com](https://www.pricecharting.com/game/wii/deal-or-no-deal?utm_source=openai))
- Halo 4 (Xbox 360) — Loose: 6.96; Complete: 7.57; New: 18.68. ([pricecharting.com](https://www.pricecharting.com/game/xbox-360/halo-4))
- Darksiders (Xbox

OPENAI_API_KEY loaded: True
sk-pr
I looked up current used-market prices and recorded the PriceCharting estimates (they aggregate completed sales). Prices were checked on December 22, 2025 (United States). Below I show the common used categories — Loose (disc only) and Complete (game + box + manual) — with the PriceCharting source for each.

- Wii Sports (Wii) — Loose: $25.26; Complete: $28.57. ([pricecharting.com](https://www.pricecharting.com/game/wii/wii-sports?utm_source=openai))  
- Wii Play (Wii) — Loose: $7.20; Complete: $7.95. ([pricecharting.com](https://www.pricecharting.com/game/wii/wii-play?utm_source=openai))  
- The Sims 3 (Wii) — Loose: $5.94; Complete: $7.30. ([pricecharting.com](https://www.pricecharting.com/game/wii/the-sims-3?utm_source=openai))  
- Deal or No Deal (Wii) — Loose: $3.82; Complete: $5.61. ([pricecharting.com](https://www.pricecharting.com/game/wii/deal-or-no-deal?utm_source=openai))  
- Halo 4 (Xbox 360) — Loose: $6.96; Complete: $7.57. ([pricecharting.com](https://www.pricecharting.com/game/xbox-360/halo-4))  
- Darksiders (Xbox 360) — Loose: $5.25; Complete: $7.01. ([pricecharting.com](https://www.pricecharting.com/game/xbox-360/darksiders?utm_source=openai))

Notes:
- PriceCharting bases these on recent completed sales (so they reflect what buyers actually paid). Values can change day-to-day.
- If you want, I can instead pull (a) current active listings (e.g., eBay Buy-It-Now), (b) recent sold eBay comps, or (c) store trade-in/used prices from GameStop, Walmart, Amazon — tell me which and I’ll fetch them.

In [ ]:
def encode_image(image_path):
    with open(image_path, "rb") as image_file:
        return base64.b64encode(image_file.read()).decode("utf-8")

image_path = "images/object_1.jpg"
base64_image = encode_image(image_path)

response = client.responses.create(
    model="gpt-5-nano-2025-08-07",
    tools=[{"type": "web_search"}],
    input=[
        {
            "role": "user",
            "content": [
                { "type": "input_text", "text": "look up how much this object is worth online." },
                {
                    "type": "input_image",
                    "image_url": f"data:image/jpeg;base64,{base64_image}",
                },
            ],
        }
    ],
)

print(response.output_text)

Nice clean photo. It looks like an original Xbox One (the two-tone black shell with a glossy left panel and a ridged right panel), not an Xbox One S or Series X/S.

Current online value (US, as of Dec 21–22, 2025)
- Basic original Xbox One (no Kinect, no extra controllers, no box) in used condition: typically about $36–$50, depending on condition. New/Boxed can be around $50; flawless around $40; good around $36. ([bankmycell.com](https://www.bankmycell.com/blog/how-much-is-an-xbox-one-worth/))
- With Kinect or bundled with extras, prices can be higher (Kinect bundles can push value higher in some listings). ([bankmycell.com](https://www.bankmycell.com/blog/how-much-is-an-xbox-one-worth/))
- Pawn/third-party quotes often range broader (roughly $40–$120), with One X fetching more (median around $102) and One S around $68; original model falls somewhere in that lower-to-mid range depending on condition and extras. ([consolepawn.com](https://consolepawn.com/guides/xbox/one.html?utm_source

In [20]:
objects = """Graphics Card (GPU): NVIDIA GeForce RTX 4060 (8GB)
Appearance: A dual-fan PNY XLR8 Gaming card with "GEFORCE RTX" and "XLR8" branding visible on the side shroud.
Processor (CPU): Intel Core i5-9600K
Appearance: Not directly visible as it is under the cooler, but confirmed by the system "About" screen.
Motherboard: MSI MPG Z390 Gaming Plus[1][2][3][4][5]
Appearance: A full-sized ATX board with red and black accents. (Note: The seller lists it as a B450, but the system info "MS-7B51" identifies it as a Z390 model).
CPU Air Cooler: Cooler Master Hyper 212 RGB Black Edition
Appearance: A tall tower cooler with black-plated fins, four copper heat pipes, and an RGB-lit 120mm fan.[6]
Memory (RAM): 32GB Corsair Vengeance LPX DDR4[7][8][9][10]
Appearance: Two sticks of low-profile RAM with distinctive red/orange aluminum heat spreaders.
PC Case: Corsair 4000D Airflow (Black)
Appearance: A black mid-tower case featuring a tempered glass side panel and a front panel with a repeating triangular geometric cutout pattern.
Storage Drives: ~1.4TB total capacity
Appearance: Not visible (internal), but listed as a combination of drives totaling 1.36 TB in the system specs."""

response = client.responses.create(
    model="gpt-5-nano-2025-08-07",
    tools=[{"type": "web_search"}],
    input=f"Please find the prices for the used versions of the following objects. Just do your best to find the information. No need to clarify anything. {objects}"
)

print(response.output_text)

Prices for used variants (rough ballparks) as of December 22, 2025:

- Graphics Card: PNY GeForce RTX 4060 8GB XLR8 Gaming (dual fans)
  - Used price range: about $240–$300, with some listings around $260–$290; a few refurbished listings run higher ( ~$260–$330). ([ebay.com](https://www.ebay.com/itm/297691511538?utm_source=openai))

- CPU: Intel Core i5-9600K
  - Used price range: roughly $60–$100, with recent listings around ~$60–$90; occasional higher asks exist for mint/newer listings. ([ebay.com](https://www.ebay.com/itm/257058739576?utm_source=openai))

- Motherboard: MSI MPG Z390 Gaming Plus
  - Used price range: typically around $78–$90, with some listings near $70–$120 depending on condition and seller. ([ebay.com](https://www.ebay.com/p/18025714341?utm_source=openai))

- CPU Air Cooler: Cooler Master Hyper 212 RGB Black Edition
  - Used price range: about $20–$45 commonly; many listings in the $20s to low $40s, some open-box or with extras command a bit more. ([ebay.com](https

Gemini -> list out everything in detail
Chat -> search internet for consevrative value

add up chat results
entry in a database for combined value